# Generated by Django 4.0.2 on 2022-02-17 04:16

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDrive',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('create_date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('manufacturer', models.TextField(blank=True, default='')),
                ('hard_drive_type', models.TextField(blank=True, default='')),
                ('hard_drive_size', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('serial_number', models.TextField(blank=True, default='')),
                ('classification', models.TextField(blank=True, default='')),
                ('image_verion_id', models.TextField(blank=True, default='')),
                ('boot_test_expiration', unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now)),
                ('boot_test_status', models.TextField(blank=True, default='')),
                ('justification_for_hard_drive_status_change', models.TextField(blank=True, default='')),
                ('connection_port', models.TextField(blank=True, default='')),
                ('issue_date', unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now)),
            ],
        ),
    ]
